### ISSUE TITLE
Cant parse response 

### ISSUE THREAD

**Issue by Mirza-Obaid** [Gerfaut/yelpv3-php#1]
```
$client = new Gerfaut\Yelp\Client(array(
        'consumerKey' => 'xxxxxxxxx',
        'consumerSecret' => 'xxxxxxx',
        'apiHost' => 'api.yelp.com' // Optional, default 'api.yelp.com'
    ));

$results = $client->search(array('term' => 'Sushi', 'location' => 'Chicago, IL'));

var_dump($results->rating);
```

i only want rating and reviewCount but its returning error 
Cannot use object of type Gerfaut\Yelp\Model\BusinessesResponse as array

**Comment by Gerfaut** [comment]
Hi @Mirza-Obaid and thank you for your issue report. 
The result of the search method is an BusinessesResponse which contains the following fields : 
- Region (Region object)
- Total (int)
- Businesses (Business[]) 

Thus, if you want to access the rating property on the first business, you can do the following : 
```
$results = $client->search(array('term' => 'Sushi', 'location' => 'Chicago, IL'));

var_dump($results->getBusinesses()[0]->getRating()); //returns a double 
```

Or if you want to access all the businesses results, you can simply use a foreach on `$results->getBusinesses()` array. 

More information in the official Yelp documentation: https://www.yelp.com/developers/documentation/v3/business_search

Thanks, 

_Gerfaut_
